<?php include _X_LAYOUT . '/welcome/header.phtml';?>
<div class="main">
    <h1>Welcome CS8</h1>
</div>
<h2>Example1 - route with prefix, post and pre processor </h2>
<div class="p8">
    <p>
        <button onclick="history.go(-1)"> &langle; back</button>
    </p>
    <b>.route.php</b>
    <p class="code">
        &lt;php
        use Scripts\Test\Test;


        // [ '[url]' => '[class] @ [method/action] | [route name]']
        routing(['test/:id/user/:user' => 'welcome/test@example1|welcome.example1'])
        // url prefix
        ->prefix('welcome')
        //pre-processor
        ->before(['welcome_model@cors', [Test::class, 'show']])
        //post processor
        ->after(['welcome_model@json']);

    </p>
    <b>
        Explains:
    </b>
    <dl>
        <dt>'test/:id/user/:user'</dt>
        <dd>url path.</dd>
        <dt>':id' and ':user'</dt>
        <dd>pass in parameters as 'id' and 'user'.</dd>
        <dt>'welcome/test@example1|welcome.example1'</dt>
        <dd>controller class: welcome/testController; action method: example1(); and router name: welcome.example1</dd>
        <dt>->prefix('welcome')</dt>
        <dd>all url path will have 'welcome/' add in front of them </dd>
        <dt>->before(['welcome_model@cors', [Test::class, 'show']])</dt>
        <dd>pre-processors: method cros() in model class 'welcome_model' and method show() of test class</dd>
        <dt>->after(['welcome_model@json']);</dt>
        <dd>post processors, same as pre-processors</dd>
    </dl>
    <pre>
        <?php print_r($data);?>
    </pre>
</div>
<?php include _X_LAYOUT . '/welcome/footer.phtml';?>