
<footer class="footer container-fluid mt-5">
	<div class="justify-content-center row ">
		<ul class="">
			<li class="list-inline-item"><p class="text-center text-muted">&copy; 2016 All rights reserved</p></li>
			<li class="list-inline-item">
				<a href="about">About Us</a>
			</li>
			<li class="list-inline-item">
				<a href="privacy">Privacy Policy</a>
			</li>
			<li class="list-inline-item">
				<a href="terms">Terms And Conditions</a>
			</li>
			<li class="list-inline-item">
				<a href="disclaimer">Disclaimer</a>
			</li>
			<li class="list-inline-item">
				<a href="contact">Contact Us</a>
			</li>
		</ul>

	</div>
</footer>

<!-- go top button -->
<button onclick="$(this).hide(); window.scroll({ top: 0, left: 0, behavior: 'smooth' });" id="gotop" title="Go to top" ><i class="fa fa-arrow-circle-up "></i></button>
<style>
#gotop {
display: none;
position: fixed;
bottom: 20px;
right: 30px;
z-index: 99;
border: none;
outline: none;
background: transparent;
color:orange;
cursor: pointer;
font-size:3em;
opacity:0.7;
}
</style>
<!-- -->

<script>
$(document).ready(function(){
	var p = 1*$('.footer.container-fluid').offset().top
	var s = 1*$('.footer.container-fluid').height()
	var h = 1*$(window).height();
	if(p+s+30 < h){
		$('.footer.container-fluid').css({"padding-top":h-s-p-20})
	}

	//go top button
        $( window ).scroll(function() {
		//_d(document.body.scrollTop);
		//_d(document.documentElement.scrollTop);
            if (document.body.scrollTop > 120 || document.documentElement.scrollTop > 120) {
		   $("#gotop").show();
            } else {
		  $("#gotop").hide();
            }
    	});

})
</script>

<style>
html { height:101%;}
</style>

</body>
</html>
