<!DOCTYPE html>
<html lang="en">

<head>
	<title><?=$page_title;?></title>
	<meta charset="utf-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=Edge" />
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<meta name="robots" content="noindex"><!-- not for admin -->

	<base href="<?=_X_URL;?>/" class="base">
	<script>
		var _PUBLIC = '<?=_X_URL_PUBLIC;?>';
		var _BASE = '<?=_X_URL;?>';
	</script>
	<meta property="og:image"
		content="<?=_route('assert', ['module'=>'sitemin', 'assert'=>'image~admin.jpg', 'version'=>0.1]);?>" />

	<link href="/media/image/micon.png" rel="shortcut icon">

	<script src="/package/jquery/jquery.js"></script>
	<!-- <script src="/js/tether.min.js"></script> -->

	<link rel="stylesheet" href="/package/jquery-ui-1.11.4/themes/smoothness/jquery-ui.css">
	<script src="/package/jquery-ui-1.11.4/jquery-ui.js"></script>


	<script src="package/bootstrap4/js/bootstrap.min.js"></script>
	<link rel="stylesheet" href="/package/bootstrap4/css/bootstrap.min.css">

	<link rel="stylesheet" href="/package/font-awesome-4.7.0/css/font-awesome.css">


	<link rel="stylesheet" href="/package/common/common.css">
	<script src="/package/common/common.js"></script>

	<script>var _keep_login = <?= (int)Helper:: data_get('sitemin,keeplogin');?>;</script>
	<link rel="stylesheet" href="<?=_route('assert', ['module'=>'sitemin', 'assert'=>'css.css', 'version'=>0.1]);?>">
	<script src="<?=_route('assert', ['module'=>'sitemin', 'assert'=>'js.js', 'version'=>0.1]);?>"></script>
</head>

<body id="page-top" class="admin <?=$page_name?>  <?=$page_title;?>">
	<?php //include __DIR__.'/nav.phtml'; ?>