<!DOCTYPE html>
<html lang="en">

<head>
	<title><?=$page_title;?></title>
	<meta charset="utf-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=Edge" />
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<meta name="robots" content="noindex"><!-- not for admin -->

	<base href="<?=_X_URL;?>/" class="base">
	<script>
		var _PUBLIC = '<?=_X_URL_PUBLIC;?>';
		var _BASE = '<?=_X_URL;?>';
	</script>
	<meta property="og:image" content="<?=_assert_url('image~admin.jpg', 'sitemin');?>" />

	<link href="/media/image/micon.png" rel="shortcut icon">

	<script src="/package/jquery/jquery.js"></script>
	<!-- <script src="/js/tether.min.js"></script> -->

	<link rel="stylesheet" href="/package/jquery-ui-1.11.4/themes/smoothness/jquery-ui.css">
	<script src="/package/jquery-ui-1.11.4/jquery-ui.js"></script>


	<script src="package/bootstrap4/js/bootstrap.min.js"></script>
	<link rel="stylesheet" href="/package/bootstrap4/css/bootstrap.min.css">

	<!--
		<link rel="stylesheet" href="/package/font-awesome-4.7.0/css/font-awesome.css">
	-->
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css">



	<link rel="stylesheet" href="/package/common/common.css">
	<script src="/package/common/common.js"></script>

	<script>var _keep_login = '<?= (int)Helper:: data_get("sitemin, keeplogin");?>';</script>
	<link rel="stylesheet" href="<?=_assert_url('css.css', 'sitemin');?>">
	<script src="<?=_assert_url('js.js', 'sitemin');?>"></script>

	<style>
		@font-face {
			font-family: "local font";
			src: url(/media/font/1942-report/1942.ttf);
		}


		html,
		body,
		h1,
		h2,
		h3,
		h4,
		h5,
		h6,
		p,
		div,
		span,
		a,
		button,
		form {
			font-family: "local font" !important;
			letter-spacing: -2px;

		}
	</style>
</head>

<body id="page-top" class="admin <?=$page_name?>  <?=$page_title;?>">