<!-- Navigation -->
<?php

/**
 * menu -- top nav bar
 */

function render_menu($menu, $level=0){
	foreach ($menu as $k=>$v){
	       //external links : no permission required
	       $v['allowed'] = ($ext = preg_match('/^http/ims', $v['router'])) ? 'allowed' : $v['allowed'];
		//not allowed router
		if($v['allowed'] !== 'allowed') continue;

		$con2 = $v['children'] ? render_menu($v['children'],$level+1): false;

		//if no router and no child don not use
		if( !$v['router']  && ! $con2) continue;

	       //external links
	       $href = ($ext ? '' : _X_URL_ROUTER ).$v['router'];
	       $target = $ext ? 'target="_blank"' : '';
	       $con1[] = '<li class="'.$v['css'].' mid_'.$v['id'].' pid_'.$v['parent_id'].' '.($v['children'] ?'has-sub up':'last').'">';
		$con1[] = $v['router'] ? "<a   href=\"{$href}\" >{$v['display']} </a>" : "<a href='#'>{$v['display']} </a>";
		if($con2) $con1[] = $con2;
		$con1[] = "</li>";
	}
	$con = '<ul class="mlevel_'.$level.' '. ($level ? 'sub-menu close':'').'">';
	$con .= implode("\n", $con1);
	$con .= '</ul>';
	return $con1 ? $con : '';
}



//check if logged in?
$current = _factory('sitemin_model_login')->current();
$menu=[];
//do not include on certain condition
if( _DO_NOT_INCLUDE_MENU === '_DO_NOT_INCLUDE_MENU'){
	$menu = _factory('sitemin_model_acl_menu')->tree();
	$menu = $menu[1]; //array_pop($menu);
	$menu = $menu['children'];
}

//add login button on nav bar
$arr =  array (
	'id' => '100000',
	'parent_id' => '1',
	'display' => $current['password'] ? 'Logout' : 'Login',
	'router' => $current['password'] ? '/sitemin/logout' : '/sitemin/login',
	'order' => '0',
	'role' => 'public,cms,designer,sitemin,admin,',
	'allowed' => 'allowed',
	'css'=>'fr',
);
array_push($menu, $arr);

//add message alert on nav bar
$arr =  array (
	'id' => '100001',
	'parent_id' => '1',
	'display' => '<span class="s_message badge badge-pill badge-secondary"><i class="fa fa-bell-o"></i><span class="badge badge-dark">0</span></span>',
	'router' => '#',
	'order' => '0',
	'role' => 'public,',
	'allowed' => 'allowed',
	'css'=>'fr',
);
array_push($menu, $arr);

$arr =  array (
    'id' => '100002',
    'parent_id' => '1',
    'display' => file_get_contents(_X_LAYOUT."/sitemin/clock.phtml"),
    'router' => '#',
    'order' => '0',
    'role' => 'public,',
    'allowed' => 'allowed',
    'css'=>'fr badge-container',
);
array_push($menu, $arr);

?>
<div class="wrapper wrapper--nav clear <?=($current['password'] ? 'logged-in' : 'logged-out');?>">
	<div class="logo px-5">Sitemin</div>
	<!--<button class="mobile">Menu toggle</button>-->
	<a class="mobile" href="javascript:void(0);"><i class="fa fa-bars" aria-hidden="true"></i></a>
	<div id="cssmenu">
		<?php // echo render_menu($menu, 0); ?>
	</div>
	<div class="clear"> </div>
</div>
<div class="nav-space-holder"></div>




<link rel="stylesheet" href="<?=_route('assert', ['module'=>'sitemin', 'assert'=>'nav.css', 'version'=>0.1]);?>">

<script>
	var open_counter = 0;
	function open_counter_change(i) {
		open_counter += i;
		if (open_counter == 0) {
			$('.sub-menu').removeClass('open').addClass('close');
			$('.down').removeClass('down').addClass('up');
		}
	}

	$(document).ready(function () {
		/**** for message alert ****/
		setTimeout(function () {
			$.ajax({
				url: "<?=_X_URL;?>/sitemin/user/message?cmd=lead",
				dataType: 'json',
				//data: $(e.form).serialize(),
				success: function (data) {
					$('.s_message .badge').html(data.unviewed)
					if (data.unviewed > 0) {
						var con = '<ul class="mlevel_1 sub-menu close">';
						for (var k in data.msg) {
							con += '<li><a href="sitemin/dashboard">' + data.msg[k].message + '</a></li>';
						}
						con += '</ul>';
						$('.s_message .badge').parent().parent().parent().append(con).click(function () { $(this).find('ul').css({ display: '' }) }).addClass('has-sub system_message');
					}

				}
			});

		}, 100);

		$('#cssmenu').on('click', '.has-sub > a', function (event) {
			event.preventDefault();
			$(this).parent().addClass('down');
			$(this).parent().siblings().removeClass('down').addClass('up');
			$(this).parent().siblings().find('.sub-menu').removeClass('open').addClass('close');
			$(this).next().removeClass('close').addClass('open');
		});

		$('#cssmenu  *').mouseover(function () { open_counter_change(1); }).mouseout(function () { setTimeout(function () { open_counter_change(-1); }, 1000) });

		//$(".sitemin-content-wrapper").css({"margin-top":$("#cssmenu").height()+"px"})

		$('.mobile').on('click', function (event) {
			$('#cssmenu').slideToggle(100);
		});


		$('.nav-space-holder').height($('.wrapper--nav').height());
	})

</script>