<!-- start of sitemin pagination -->

<!--@ Font Awesome used!! -->

<nav class="pagination">
	<ul class="nav ml-auto pagination0">
		<li class="nav-item"><span class="page-link"><?= $data['page']['length']; ?> per page</span></li>
		<li class="nav-item <?php if (!$data['page']['backward']) :  echo "sr-only";
							else : echo "first-item";
							endif; ?>">
			<a class="page-link" href="javascript:void(0)" onclick="jQuery('#page').val(1); jQuery('#filter')[0].submit();"><i class="fa fa-fast-backward" aria-hidden="true"></i></a>
		</li>
		<li class="nav-item <?php if (!$data['page']['backward']) :  echo "sr-only";
							else : echo "first-item";
							endif; ?>">
			<a class="page-link" href="javascript:void(0)" onclick="jQuery('#page').val('<?= (int)(($data['page']['no']) / 2); ?>'); jQuery('#filter')[0].submit();">
				<i class="fa fa-backward" aria-hidden="true"></i>
			</a>
		</li>
		<li class="nav-item <?php if (!$data['page']['backward']) : echo "sr-only";
							endif; ?>">
			<a class="page-link" href="javascript:void(0)" onclick="jQuery('#page').val('<?= $data['page']['no'] - 1; ?>'); jQuery('#filter')[0].submit();">
				<i class="fa fa-step-backward" aria-hidden="true"></i>
			</a>
		</li>

		<li class="nav-item <?php if (!$data['page']['backward'] || !$data['page']['omit']) : echo "sr-only  first-no";
							endif; ?> "><a class="page-link" href="#">...</a></li>
		<?php for ($i = ($data['page']['current_shows'] - 1) * $data['page']['pagination_max_length'] + 1; $i <= ($data['page']['current_shows'] - 1) * $data['page']['pagination_max_length'] + $data['page']['current_shows_length']; $i++) : ?>
			<li class="page-item <?php if ($i == $data['page']['no']) : echo "active";
									endif; ?> showed"><a class="page-link" href="javascript:void(0)" onclick="jQuery('#page').val('<?php echo $i; ?>'); jQuery('#filter')[0].submit();"><?php echo $i; ?></a></li>
		<?php endfor; ?>
		<li class="panavge-item <?php if (!$data['page']['forward']  || !$data['page']['omit']) : echo "sr-only";
								endif; ?>"><a class="page-link" href="#">...</a></li>

		<li class="panavge-item <?php if (!$data['page']['forward']) : echo "sr-only";
								endif; ?>">
			<a class="page-link" href="javascript:void(0)" onclick="jQuery('#page').val('<?= $data['page']['no'] + 1; ?>'); jQuery('#filter')[0].submit();">
				<i class="fa fa-step-forward" aria-hidden="true"></i>
			</a>
		</li>
		<li class="panavge-item <?php if (!$data['page']['forward']) : echo "sr-only";
								endif; ?>">
			<a class="page-link" href="javascript:void(0)" onclick="jQuery('#page').val('<?= $data['page']['no'] + (int)(($data['page']['pages'] - $data['page']['no']) / 2); ?>'); jQuery('#filter')[0].submit();">
				<i class="fa fa-forward" aria-hidden="true"></i>
			</a>
		</li>
		<li class="panavge-item <?php if (!$data['page']['forward']) : echo "sr-only";
								endif; ?>">
			<a class="page-link" href="javascript:void(0)" onclick="jQuery('#page').val('<?= $data['page']['pages']; ?>'); jQuery('#filter')[0].submit();">
				<i class="fa fa-fast-forward" aria-hidden="true"></i>
			</a>
		</li>
	</ul>

</nav>
<!-- end of sitemin pagination -->