<!DOCTYPE html>
<html lang="en">
<head>
	<title><?=$page_title;?></title>
	<meta charset="utf-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=Edge"/>
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<meta name="robots" content="noindex"><!-- not for admin -->


	<base href="<?=_X_URL;?>/" class="base">
	<script>
		var _PUBLIC='<?=_X_URL_PUBLIC;?>';
		var _BASE='<?=_X_URL;?>';
		var _URL='<?=_r_url();?>';
	</script>

	<meta property="og:image" content="public/media/image/admin.jpg" />

	<link href="publicss/media/image/micon.png" rel="shortcut icon">

	<script src="public/package/jquery/jquery.js"></script>
	<!-- <script src="/js/tether.min.js"></script> -->

	<link rel="stylesheet" href="public/package/jquery-ui-1.11.4/themes/smoothness/jquery-ui.css">
	<script src="public/package/jquery-ui-1.11.4/jquery-ui.js"></script>


	<script src="public/package/bootstrap4/js/bootstrap.min.js"></script>
	<link rel="stylesheet" href="public/package/bootstrap4/css/bootstrap.min.css">

	<link rel="stylesheet" href="public/package/font-awesome-4.7.0/css/font-awesome.css">

	<link rel="stylesheet" href="public/package/common/common.css">
	<script src="public/package/common/common.js"></script>

</head>
<body id="page-top" class="admin <?=$page_name?>  <?=_alter($page_title);?>" >
