<?php include _X_LAYOUT . '/welcome/header.phtml'; ?>
<div class="main">
    <h1>Welcome CS8</h1>
</div>
<h2>Example2 - simple</h2>
<div class="p8">
    <p>
        <button onclick="history.go(-1)"> &langle;  back</button>
    </p>
    <b>.route.php</b>
    <p class="code">
        &lt;php
        

        use modules\welcome\exampleController;

        // [ '[url]' => [ [class], [method/action], [route name]']
        routing(['examples/post/:id' => [exampleController::class, 'example2', 'welcome.example2']])
        // url prefix
        ->prefix('welcome');

    </p>
</div>
<?php include _X_LAYOUT . '/welcome/footer.phtml'; ?>