<?php include _X_LAYOUT . '/welcome/header.phtml';?>
<div class="main">
    <h1>Welcome CS8</h1>
</div>
<h2>Example - helper functions</h2>
<div class="p8">
    <p>
        &langle; <a href="<?=_routes('welcome');?>"> back</a>
    </p>
    <ol>
        <li>Start the application using one of the following methods:
            <ol>
                <li>Command Line Interface (CLI): <span class="code">$ php exec "route" param1 param2....</span></li>
                <li>HTTP call to the "route" with browser or API. e.g. "route" : welcome/examples/page/5
                    <span class="code">http://localhost:8888/welcome/examples/page/5</span>
                </li>
            </ol>
        </li>
        <li>Initialize the system at "public/index.php."</li>
        <li>Load the main application by <span class="code">$app = new App();</span>
            <ol>
                <li>Load "define.php."</li>
                <li>Load ".local.php" (local settings).</li>
                <li>Load system files: helper, logger, router, controller, etc.</li>
                <li>Load local routes from enabled modules:
                </li>
                <li> Load model overwrites from the "config/overwrite/" folder.</li>
                <li>Find the controller based on the defined routes(all .route.php in enabled modules).</li>
                <li>Prepare the data using the _request() function.</li>
                <li>Call pre-processors if route defines</li>
                <li>Call the controller.</li>
                <li>Optionally, the controller may call models to prepare data.</li>
                <li>Call post-processors if route defines</li>
                <li>Return data or call a view file based on the controller's return.</li>
                <li>* if no view, the pre and post will not included in the result.</li>
            </ol>
        </li>
    </ol>
</div>
<?php include _X_LAYOUT . '/welcome/footer.phtml';?>