<?php include _X_LAYOUT . '/welcome/header.phtml';?>
<div class="main">
    <h1>Welcome CS8</h1>
</div>
<h2>Example - helper functions</h2>
<div class="p8">
    <p>
        &langle; <a href="<?=_routes('welcome');?>"> back</a>
    </p>
    <ol>
        <li>start by one of following method
            <ol>
                <li>cli: $php exec "route" param1 param2....</li>
                <li>http call to the "route"</li>
            </ol>
        </li>
        <li>system init at "public/index.php"</li>
        <li>load main app
            <ol>
                <li>load define.php</li>
                <li>load .local.php (local setting)</li>
                <li>load system file: helper, logger, router, controller.. </li>
                <li>local all routes from enabled modules
                    <ol>
                        <li>check if there are setup file(such as setup.0.0.0.1.php, ".0.0.0.1" is the version number)
                        </li>
                        <li>run the files once according to version's order and rename them as setup.0.0.0.1.php.done
                        </li>
                    </ol>
                </li>
                <li>load models overwrites from "config/overwrite/" folder</li>
                <li>find the controller by routes</li>
                <li>prepare _request() data</li>
                <li>call controller</li>
                <li>*controller may call models to prepare the data - optional</li>
                <li>return data or call view file according to controller's return</li>
            </ol>
        </li>
    </ol>
</div>
<?php include _X_LAYOUT . '/welcome/footer.phtml';?>