<?php include _layout() . '/header.phtml';?>

<h2>URL: assert _route()</h2>
<div class="p8">

    <b>Special route a=called 'assert' for helping push the assert to public</b>
    <pre class="code">
        echo _assert_url('welcome.css', 'welcome_example', 1.21);

        # => http:://DOMAIN/assert/welcome_example/welcome.css/1.21
    </pre>
    <pre>
        and this will get assert form _X_MODULE . "/welcome/example/assert/welcome.css"

        e.g. 
        &lt;link rel="stylesheet" 
            type="text/css" 
            href="&lt;?=_assert_url('welcome.css', 'welcome_example',1.12);?&gt;"&gt;
    </pre>

    <pre>
        Sub-folder in assert Folder, use "~" to replace "/"
        e.g. 
        _assert_url('images~admin.jpg', 'welcome_example');

        'images~admin.jpg' : 'images/admin.jpg'

    </pre>






</div>
<?php include _layout() . '/footer.phtml';?>