<?php include _layout() . '/header.phtml';?>

<h2>Example - helper functions</h2>
<div class="p8">


    download code from github https://github.com/stone256/cs8 to your web-server document-root folder
    or you can run php server under public folder in console with <b><i>php -S allowed-ip:port</i></b>
    <span class="code">
        $cd src/public
        $ php -S 0.0.0.0:8900
    </span>
    then browse at after the setup
    http://localhost:8900

    copy config/local.example.php to config/local.php and make change whatever the changes you need.

    change the .composer.json to load all 3rd party plugin you need.

    <span class="code">
        $composer install
    </span>



</div>
<?php include _layout() . '/footer.phtml';?>