<?php include _X_LAYOUT . '/welcome/header.phtml';?>
<?php $_debug=0;?>
<div class="main">
    <h1>Welcome CS8</h1>
</div>
<h2>Example - Modules</h2>
<div class="p8">
    <p>
        <a href="<?=_routes('welcome');?>" > &langle; back</a>
    </p>
        <table border=0 width=100%>
            <tr>
                <td><b>Module</b></td><td><b>Status</b></td><td><b>Action</b></td>
            </tr>
            <!-- active modules -->
            <?php foreach ($data['active'] as $module): ?>
            <tr>
                <td><?=$module;?></td>
                <td>Active</td>
                <td>
                    <?php if (in_array($module, $data['example only'])): ?>
                        <i>System Example</i>
                    <?php else: ?>
                        <a href="<?=_routes('welcome.modules.disable');?>?_csrf=<?=$data['_csrf'];?>&m=<?=$module;?>" >disable it</a> 
                    <?php endif;?>
                </td>
            </tr>
            <?php endforeach;?>

            <!-- inactive modules -->
            <?php foreach ($data['inactive'] as $module): ?>
            <tr>
                <td><?=$module;?></td>
                <td>inactive</td>
                <td>
                <?php if (in_array($module, $data['example only'])): ?>
                    <i>System Example</i>
                <?php else: ?>
                    <a href="<?=_routes('welcome.modules.enable');?>?_csrf=<?=$data['_csrf'];?>&m=<?=$module;?>" >enable it</a> 
                <?php endif;?>
                </td>
            </tr>
            <?php endforeach;?>
        </table>
</div>
<?php include _X_LAYOUT . '/welcome/footer.phtml';?>