<?php include _X_LAYOUT . '/welcome/header.phtml';?>
<?php $_debug=0;?>
<div class="main">
    <h1>Welcome CS8</h1>
</div>
<h2>Example - Modules - install (zip file)</h2>
<div class="p8">
    <p>
        <a href="<?=_routes('welcome');?>" > &langle; back</a>
    </p>

    





    <!-- use bootstrap-->
    <script>

    </script>
        <h3>
            install requires write permission of following folders:
        </h3>
        <ul>
            <li> layout</li>
            <li> config/enabled</li>
            <li> modules</li>
            <li> public</li>
        </ul>
        <h3 class="text-uppercase mt-5">Install Zipped Module</h3>
 














</div>
<?php include _X_LAYOUT . '/welcome/footer.phtml';?>