<?php include _layout() . '/header.phtml';?>
<div class="main">
    <h1>Welcome CS8</h1>
</div>
<h2>Example1 - route with prefix, post and pre processor </h2>
<div class="p8">
    <p>
        &langle; <a href="<?=_route('welcome');?>"> back</a>
    </p>
    <b>modules/welcome/example/.route.php</b>
    <p class="code">
        &lt;php

        use modules\welcome\example\exampleController;
        use modules\welcome\scripts\Test\Test;

        // simple routing
        routing([
        '' => 'welcome/example/index@index',
        '/' => 'welcome/example/index@index',
        '/welcome' => 'welcome/example/index@index',
        ]);


        // routing with prefix and pre and post processor
        routing([
        'test/:id/user/:user' => 'welcome/example/test@example1|welcome.example1',
        ])
        ->prefix('welcome')
        ->before(['welcome_example_model@cors', [Test::class, 'show']])
        ->after(['welcome_example_model@json']);


        // use class type
        routing(['/welcome/examples/post/:id' => [exampleController::class, 'example2', 'welcome.example2']]);

        // use string type
        routing(['/welcome/modules/list' => 'welcome/module/index@list|welcome.modules.list']);


    </p>
    <b>
        Explains:
    </b>
    <dl>
        <dt>'test/:id/user/:user'</dt>
        <dd>url path.</dd>
        <dt>':id' and ':user'</dt>
        <dd>pass in parameters as 'id' and 'user'.</dd>
        <dt>'welcome/example/test@example1|welcome.example1'</dt>
        <dd>controller class: welcome/example/testController; action method: example1(); and router name:
            welcome.example1</dd>
        <dt>->prefix('welcome')</dt>
        <dd>all url path will have 'welcome/' add in front of them </dd>
        <dt>->before(['welcome_model@cors', [Test::class, 'show']])</dt>
        <dd>pre-processors: method cros() in model class 'welcome_model' and method show() of test class</dd>
        <dt>->after(['welcome_model@json']);</dt>
        <dd>post processors, same as pre-processors</dd>
        <dt>*note</dt>
        <dd>you can not mix use of string type and class type routing for one controller. but can mix them for different
            controllers</dd>
    </dl>
    <pre>
        <?php print_r($data);?>
    </pre>
</div>
<?php include _layout() . '/footer.phtml';?>