<?php include _layout() . '/header.phtml';?>
<div class="main">
    <h1>Welcome CS8</h1>
</div>
<h2>Routing and Controller</h2>
<div class="p8">
    <p>
        &langle; <a href="<?=_route('welcome');?>"> back</a>
    </p>
    <b>.route.php</b>
    <p class="code">
        &lt;php


        use modules\welcome\example\exampleController;

        # type class [ "url" => [ "class", "handle-method", "route name"]
        routing(['examples/post/:id' => [exampleController::class, 'example2','welcome.example2']]);



        # type string [ "url" => "module-path-to-class/controller-name@handle-method|route name"]
        routing(['simple/articles/:id' => "simple/index@articles|simple.article"]);

        ## the controller-name worked as:
        ## "simple/product@find" refers to "function find(){}" in "modules/simple/productController.php"
    </p>

    <pre>

        <b>examples/post/:id</b> is the url-path, ':id' in the url-path is to pass in the as id

        the  http://[xxxx.xxx.xxx]/welcome/examples/post/123

        will pass in <i>id = 123</i>
    <h3>
        You can change the number in url
        and give a try

        current <i class="error">id = <?=$data['id'];?></i>
    </h3>



    </pre>

</div>
<?php include _layout() . '/footer.phtml';?>