<?php include _layout() . '/header.phtml';?>

<h2>Example - console commands</h2>
<div class="p8">

    <pre>
        system provide a way to allow you call a controller from console command line, similar to you browser the url with some differences:
    </pre>

    <p class="code">
        browser
        $ http://localhost:8888/<b>welcome/examples/console?a=1&b=2&userId=8&product&category</b>
    </p>

    <p class="code">
        ## command line
        $ php exec <b>/welcome/examples/console a=1 b=2 userId=8 product category</b>
    </p>
    <pre class="structure">
        <h3>explains</h3>
        - run under src folder
        $ php exec <b><u>welcome/examples/console</u>  <u>a=1 b=2 userId=8 product category</u></b>
                           &boxv;                        &boxv; 
        route:&boxh;&boxh;&boxh;&boxh;&boxh;&boxh;&boxh;&boxh;&boxh;&boxh;&boxh;&boxh;&boxh;&boxul;                        &boxv; 
                                                    &boxv; 
        all query parameters: &boxh;&boxh;&boxh;&boxh;&boxh;&boxh;&boxh;&boxh;&boxh;&boxh;&boxh;&boxh;&boxh;&boxh;&boxh;&boxh;&boxh;&boxh;&boxh;&boxh;&boxh;&boxh;&boxul;

        the contains of _request()  would be
        {
            "a": "1",
            "b": "2",
            "useId": "8",
            "0": "product",
            "1": "category",
            "__start__": 1697083173.723353
        }

        __start__ = start in microtime(1);

        - A parameter specified with '=' will be interpreted as a key=>value pair, 
        - While a parameter without '=' will be treated as a numeric index in a continuous sequence.


        When executed in a web browser at the URL http://cs8.mx21/welcome/examples/console?a=1&b=2&0=code&mx=yes&1=debug 
        the following message is displayed:

        <b class="error">Unauthorized: Access to the resource is denied.</b>

        this is because in the controller we have the line <i>$this->is_cli();</i>, that allows console only:
        <p class="code">
            class welcome_examples_consoleController <b>extends _system_default</b> 
            public function console_command()
            {
                <i>$this->is_cli();</i>
    
        </p>

    </pre>

    <pre>
        Of cause, you can always use curl or other type http clients... 
    </pre>
</div>
<?php include _layout() . '/footer.phtml';?>