<?php include _layout() . '/header.phtml';?>
<?php $_debug=0;?>

<h2>Example - Modules list</h2>
<div class="p8">


    <p class="code">

        public function example()
        {
        &nbsp;&nbsp;&nbsp;&nbsp;return ['data' => _module()];
        }

        #by call helper function _module(), get all modules
    <pre>

        (
            [all] => Array
                (
                [0] => /dummy
                [1] => /welcome/example
                [2] => /welcome/module/activeTest
                [3] => /welcome/module/disabled
                [4] => /welcome/module/enabled
                )

            [active] => Array
                (
                [0] => /dummy
                [1] => /welcome/example
                [2] => /welcome/module/enabled
                )

            [inactive] => Array
                (
                [0] => /welcome/module/activeTest
                [1] => /welcome/module/disabled
                )

        )
        </pre>

    </p>

    <table border=0 width="80%">
        <tr>
            <td><b>Module</b></td>
            <td><b>Status</b></td>
        </tr>
        <!-- active modules -->
        <?php foreach ($data['active'] as $module): ?>
        <tr>
            <td><?=$module;?></td>
            <td>Active</td>
        </tr>
        <?php endforeach;?>

        <!-- inactive modules -->
        <?php foreach ($data['inactive'] as $module): ?>
        <tr>
            <td><?=$module;?></td>
            <td>inactive</td>
        </tr>
        <?php endforeach;?>
    </table>
</div>
<?php include _layout() . '/footer.phtml';?>