<?php include _X_LAYOUT . '/welcome/header.phtml';?>
<div class="main">
    <h1>Welcome CS8</h1>
</div>
<h2>Example - simple</h2>
<div class="p8">
    <p>
        &langle; <a href="<?=_routes('welcome');?>"> back</a>
    </p>
    <b>.route.php</b>
    <p class="code">
        &lt;php


        use modules\welcome\example\exampleController;

        // [ '[url]' => [ [class], [method/action], [route name]']
        routing(['examples/post/:id' => [exampleController::class, 'example2', 'welcome.example2']])
        // url prefix
        ->prefix('welcome');

    </p>

    <pre>

        <b>examples/post/:id</b> is the url-path, ':id' in the url-path is to pass in the as id

        the  http://[xxxx.xxx.xxx]/welcome/examples/post/123

        will pass in <i>id = 123</i>
    <h3>
        You can change the number in url
        and give a try

        current <i class="error">id = <?=$data['id'];?></i>
    </h3>
    </pre>

</div>
<?php include _X_LAYOUT . '/welcome/footer.phtml';?>