<?php include _X_LAYOUT . '/welcome/header.phtml';?>
<div class="main">
    <h1>Welcome CS8</h1>


</div>
<div class="p8">
    <ul>
        <li>
            <a href="<?=_routes('welcome.example5');?>"> example : folder structure</a>
        </li>
        <li>
            <a href="<?=_routes('welcome.example2', ['id' => 100, 'user' => 1009]);?>"> example : routing -
                simple</a>
        </li>
        <li>
            <a href="<?=_routes('welcome.example1', ['id' => 2, 'user' => 88]);?>"> example : routing - full </a>
        </li>
        <li>
            <a href="<?=_routes('welcome.example4');?>"> example : standard model over-write</a>
        </li>
        <li>
            <a href="<?=_routes('welcome.example3');?>"> example : console commands</a>
        </li>

        <li>
            <a href="<?=_routes('welcome.example6');?>"> example : module install, uninstall</a>
        </li>

        <li>
            <a href="<?=_routes('welcome.example7');?>"> example : module enable, disable</a>
        </li>
        <li>
            <a href="<?=_routes('welcome.example8');?>"> example : module list</a>
        </li>
        <li>
            <a href="<?=_routes('welcome.example9');?>"> example : helper functions</a>
        </li>
        <li>
            <a href="<?=_routes('welcome.sample', ['id'=>1]);?>"> how it's put together ?</a>
        </li>
    </ul>
</div>
<?php include _X_LAYOUT . '/welcome/footer.phtml';?>