<?php include _X_LAYOUT . '/welcome/header.phtml';?>
<div class="main">
    <h1>Welcome CS8</h1>
</div>
<div class="p8">
    <div class='some-page-wrapper'>
        <div class='row'>
            <div class='column'>

            </div>

            <div class='column index'>
                <ul>
                    <li class="b1">
                        <a href="<?=_routes('welcome.sample', ['id'=>0]);?>"> Install App</a>
                    </li>
                    <li class="b">
                        <a href="<?=_routes('welcome.example5');?>"> Folder structure</a>
                    </li>
                    <li class="b">
                        <a href="<?=_routes('welcome.sample', ['id'=>6]);?>"> Hello World</a>
                    </li>
                    <li>
                        <a href="<?=_routes('welcome.sample', ['id'=>1]);?>"> How it's put together ?</a>
                    </li>
                    <li class="b">
                        <a href="<?=_routes('welcome.example2', ['id' => 100, 'user' => 1009]);?>"> Routing and
                            Controllers</a>
                    </li>
                    <li class="b">
                        <a href="<?=_routes('welcome.example1', ['id' => 2, 'user' => 88]);?>"> Routing - full
                            description </a>
                    </li>
                    <li class="b">
                        <a href="<?=_routes('welcome.sample', ['id'=>7]);?>"> Controllers</a>
                    </li>
                    <li class="b">
                        <a href="<?=_routes('welcome.sample', ['id'=>2]);?>"> Where do i find/put view ?</a>
                    </li>
                    <li class="b">
                        <a href="<?=_routes('welcome.sample', ['id'=>3]);?>"> Using model / factory function</a>
                    </li>
                    <li>
                        <a href="<?=_routes('welcome.example4');?>"> Model(standard type) over-write</a>
                    </li>


                </ul>
            </div>
            <div class='column index'>
                <ul>

                    <li>
                        <a href="<?=_routes('welcome.example3');?>"> Run console commands</a>
                    </li>

                    <li>
                        <a href="<?=_routes('welcome.example6');?>"> Module install, uninstall</a>
                    </li>

                    <li>
                        <a href="<?=_routes('welcome.example7');?>"> Module enable, disable</a>
                    </li>
                    <li>
                        <a href="<?=_routes('welcome.example8');?>"> Module list</a>
                    </li>
                    <li>
                        <a href="<?=_routes('welcome.example9');?>"> Some console commands</a>
                    </li>


                    <li>
                        <a href="<?=_routes('welcome.sample', ['id'=>4]);?>"> Using system log</a>
                    </li>
                    <li>
                        <a href="<?=_routes('welcome.sample', ['id'=>5]);?>"> More Helper functions</a>
                    </li>
                </ul>
            </div>

            <div class='column'>

            </div>
        </div>
    </div>




</div>
<?php include _X_LAYOUT . '/welcome/footer.phtml';?>