<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">

  <meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate" />
  <meta http-equiv="Pragma" content="no-cache" />
  <meta http-equiv="Expires" content="0" />

  <title>welcome | cs8</title>
  <link rel="stylesheet" type="text/css" href="<?=_assert_url('welcome.css', 'welcome_example');?>">
</head>

<body>
  <div class="main">
    <?php if($index_page ?? false): ?>
    <h1>Welcome CS8</h1>
    <?php else: ?>
    <h1><a href="<?=_route('welcome');?>">Welcome CS8</a></h1>
    <?php endif ?>
  </div>