<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">

  <meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate" />
  <meta http-equiv="Pragma" content="no-cache" />
  <meta http-equiv="Expires" content="0" />

  <title>welcome | cs8</title>
  <link rel="stylesheet" type="text/css"
    href="<?=_route('assert', ['module'=>'welcome_example','assert'=>'welcome.css', 'version'=>1]);?>">
</head>

<body>