
<br><br>
<div class="row justify-content-center">
        <div class="modal-content col-6">
                        <div id="time-bar3" data-time="30" ></div>
                        <div class="modal-header  login-logo">
                                <div class="row">
                                        <h3 class="">QR Code Generator</h3>
                                        <br>
                                        <div class="">* When suggested app lead to google app store on desktop PC, and there is not barcode for phone?!</div>
                                </div>
                        </div>
                        <div class="modal-body text-center">
                                        <input type="text" placeholder="contents" required="" name="hints" class="form-control input-lg" id="contents">
                                </br>
                                        <button type="button" value="1" name="save" class="btn btn-lg btn-alert" onclick="qrcode()" id="save">
                                                <span>Generate</span>
                                        </button>
                                        <p>Thanks for <a href="http://goqr.me/">http://goqr.me/</a></p>
                                <br/><br/>
                                <div class="Hide status"></div>

                        </div>
                </div>
        </div>
</div>

<script>
function qrcode(){
        common.mask.up();
        var con = $('#contents').val() || window.location.href;
        var api = 'https://api.qrserver.com/v1/create-qr-code/?data=' + encodeURIComponent(con);

        $('.status').html('').show().append('<img src="'+api+'" onload="common.mask.down()" />')
}

(function(){
        //common.time_bar.init('#time-bar3');
})()
</script>
